### ISSUE TITLE
impl: Navigation Bar

### ISSUE THREAD

**Issue by Ebooher** [COSC481W-2021Fall/capstone-7-Deadly-Bugs#62]
When I am accessing pages I want a navigation bar that contains navigation and interactions relevant to each page.

Acceptance Criteria:
1. have a nav bar on view, edit and load page
2. put buttons for navigation into the bar

Tasks:
1. Implement navigation through the buttons on the nav bar
2. Create buttons 
3. Make consistent position for the nav bar

**Comment by Emiliano-Russo** [comment]
i'll try this
