### ISSUE TITLE
Sprint 4 Pre-sprint Maintenance

### ISSUE THREAD

**Issue by rrstem** [COSC481W-2021Fall/capstone-7-Deadly-Bugs#80]
This is a maintenance PBI to clean up the code and fix minor bugs before we get started on sprint 4.

TASKS:

- [x] 1. On backend, move all the methods relating to manipulating decks to decks.go, as main.go is getting cluttered
- [x] 2. Consistent code styling on the frontend. It just looks really messy right now.
- [x] 3. Some better documentation on frontend.
- [x] 4. Remove unnecessary console.logs && fmt.Printlns from production code.
- [x] 5. Remove the duplicate homepage in App.js
- [x] 6. Cleanup compiler warnings on frontend
- [x] 7. Replace backend mongodb calls to get certain collections with static vars of the collections.
- [x] 8. Replace panics on backend with either error logs or proper error handling.
- [x] 9. Remove the getSecret request (it was just test code)
- [x] 10. Not all `<a>` tags should look like buttons -- there should be a class for this.
- [x] 11. Fix new NPM error that is messing with everyone's development environments.
- [x] 12. Fix first login not populating name and profile picture.
- [x] 13. Update profile page to use deck previews
- [x] 14. Check if a deck is private on the profile page before trying to display it.

**Comment by emich-kyle** [comment]
I can do 1, 2, and 6

**Comment by rrstem** [comment]
working on 5

**Comment by rrstem** [comment]
working on 12

**Comment by mzindah** [comment]
I can do 4 and 14.

**Comment by phoenixffire** [comment]
I'll start working on 8.

**Comment by rrstem** [comment]
will do 7 later tonight
